version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "OpenFisca-UK"
        dependency-type: "direct"
      - dependency-name: "OpenFisca-US"
        dependency-type: "direct"
