name: Push

on: 
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          options: ". -l 79 --check"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: make install
      - name: Run the main tests
        run: make test
  publish:
    name: Deploy
    if: github.repository == 'PolicyEngine/policyengine-core'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: make install
      - name: Install datasets
        run: make datasets
      - name: Build server package
        run: make build-server
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
          skip_existing: true
          packages_dir: policyengine/dist/
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build client package
        run: make build-client
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: client/package.json
      - name: Deploy app
        run: make deploy